#!/usr/bin/env python3
"""
Profile agent: lets the orchestrator (service) push/pull the Chrome profile as a
plaintext tar.gz, so persistence (incl. IndexedDB + Service Worker) survives a
pod restart as one consistent unit.

The ORCHESTRATOR owns S3 + encryption: it decrypts before PUT and encrypts after
GET, so no keys ever live in the pod.

Endpoints (bound on PROFILE_AGENT_PORT, default 9224):
  GET  /health           -> 200 "ok" once the agent is up
  PUT  /profile          -> body is a tar.gz of the profile; extracted into
                            SESSION_DATA_PATH, then /tmp/profile_ready is touched
                            so start.sh knows it may launch Chrome (restore done)
  GET  /profile          -> streams a tar.gz of SESSION_DATA_PATH (caches excluded)

Auth: if PROFILE_TOKEN (or DEVTOOLS_TOKEN) is set, requests must carry
``Authorization: Bearer <token>``. In-cluster only; same trust model as the CDP port.
"""
import os
import subprocess
import http.server
import socketserver

SESSION_DATA_PATH = os.environ.get("SESSION_DATA_PATH", "/session-data")
PORT = int(os.environ.get("PROFILE_AGENT_PORT", "9224"))
TOKEN = os.environ.get("PROFILE_TOKEN") or os.environ.get("DEVTOOLS_TOKEN") or ""
READY_FLAG = "/tmp/profile_ready"

# Runtime lock files that record the owning process/host. If restored, Chrome
# thinks the profile is "in use by another Chromium process on another computer"
# and refuses to start (crash loop). Must never be persisted; also stripped on
# extract below so already-saved profiles are usable.
LOCK_FILES = ["SingletonLock", "SingletonCookie", "SingletonSocket"]

# Directories regenerated by Chrome — never worth persisting (10x the size for nothing).
TAR_EXCLUDES = LOCK_FILES + [
    "Default/Cache",
    "Default/Code Cache",
    "Default/GPUCache",
    "Default/DawnGraphiteCache",
    "Default/DawnWebGPUCache",
    "Default/Service Worker/CacheStorage",
    "Default/Service Worker/ScriptCache",
    "Default/GraphiteDawnCache",
    "Default/ShaderCache",
    "GraphiteDawnCache",
    "ShaderCache",
    "GrShaderCache",
    "component_crx_cache",
]


class Handler(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def _authed(self) -> bool:
        if not TOKEN:
            return True
        return self.headers.get("Authorization", "") == f"Bearer {TOKEN}"

    def _deny(self):
        self.send_response(401)
        self.send_header("Content-Length", "0")
        self.end_headers()

    def log_message(self, *args):  # quiet
        pass

    def do_GET(self):
        if self.path == "/health":
            body = b"ok"
            self.send_response(200)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        if self.path == "/profile":
            if not self._authed():
                return self._deny()
            self._stream_profile()
            return
        self.send_response(404)
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_PUT(self):
        if self.path != "/profile":
            self.send_response(404)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        if not self._authed():
            return self._deny()
        self._extract_profile()

    def _stream_profile(self):
        """tar.gz SESSION_DATA_PATH (minus caches) to the response body."""
        args = ["tar", "czf", "-"]
        for ex in TAR_EXCLUDES:
            args.append(f"--exclude={ex}")
        # archive paths relative to SESSION_DATA_PATH
        args += ["-C", SESSION_DATA_PATH, "."]
        self.send_response(200)
        self.send_header("Content-Type", "application/gzip")
        self.send_header("Transfer-Encoding", "chunked")
        self.end_headers()
        proc = subprocess.Popen(args, stdout=subprocess.PIPE)
        try:
            while True:
                chunk = proc.stdout.read(65536)
                if not chunk:
                    break
                self.wfile.write(f"{len(chunk):X}\r\n".encode())
                self.wfile.write(chunk)
                self.wfile.write(b"\r\n")
            self.wfile.write(b"0\r\n\r\n")
        finally:
            proc.stdout.close()
            proc.wait()

    def _extract_profile(self):
        """Extract the uploaded tar.gz into SESSION_DATA_PATH, then flag ready."""
        length = int(self.headers.get("Content-Length", "0"))
        os.makedirs(SESSION_DATA_PATH, exist_ok=True)
        proc = subprocess.Popen(
            ["tar", "xzf", "-", "-C", SESSION_DATA_PATH],
            stdin=subprocess.PIPE,
        )
        remaining = length
        try:
            while remaining > 0:
                chunk = self.rfile.read(min(65536, remaining))
                if not chunk:
                    break
                proc.stdin.write(chunk)
                remaining -= len(chunk)
            proc.stdin.close()
            rc = proc.wait()
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass
            rc = 1
        ok = rc == 0
        if ok:
            # Strip any owner lock files that slipped into the archive (older saves),
            # so Chrome doesn't refuse to start ("profile in use on another computer").
            for name in LOCK_FILES:
                try:
                    os.remove(os.path.join(SESSION_DATA_PATH, name))
                except OSError:
                    pass
            # Tell start.sh the profile is in place and Chrome may launch.
            try:
                open(READY_FLAG, "w").close()
            except Exception:
                pass
        body = b"ok" if ok else b"error"
        self.send_response(200 if ok else 500)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


class ThreadingServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


if __name__ == "__main__":
    srv = ThreadingServer(("0.0.0.0", PORT), Handler)
    print(f"[profile_agent] listening on 0.0.0.0:{PORT} data={SESSION_DATA_PATH}", flush=True)
    srv.serve_forever()
